name: Run Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'  # every midnight UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run api Tests
      run: npm run api

    - name: Run e2e Tests
      run: npm run e2e

    - name: Run e2e Tests
      run: npm run visual